name: belkis_web_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  flutter_admin_scaffold: ^1.2.0
  file_picker: ^6.0.0
  flutter_easyloading: ^3.0.5
  iconly: ^1.0.1
  date_time_format: ^2.0.1
  mime_type: ^1.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: Semi-Bold
    fonts:
      - asset: assets/fonts/AkayaTelivigala-Regular.ttf

  - family: Brand-Bold
    fonts:
      - asset: assets/fonts/NotoSans-Black.ttf

  - family: Regular
    fonts:
      - asset: assets/fonts/WorkSans-Regular.ttf

  - family: Bold
    fonts:
      - asset: assets/fonts/WorkSans-SemiBold.ttf
